// Generated by CoffeeScript 1.8.0
(function() {
  var fetch, http, https, rimraf;

  rimraf = require('rimraf');

  http = require('http');

  https = require('https');

  fetch = function() {
    return https.request({
      host: 'getforge.com',
      path: '/deployed.json'
    }, function(response) {
      var str;
      str = "";
      response.on('data', function(chunk) {
        return str += chunk;
      });
      return response.on('end', function() {
        var domain, domains, _i, _len, _results;
        if (response.statusCode === 200) {
          domains = JSON.parse(str);
          _results = [];
          for (_i = 0, _len = domains.length; _i < _len; _i++) {
            domain = domains[_i];
            rimraf("/tmp/cache/" + domain, (function(_this) {
              return function() {};
            })(this));
            _results.push(rimraf("/tmp/cache/www." + domain, (function(_this) {
              return function() {};
            })(this)));
          }
          return _results;
        }
      });
    }).end();
  };

  fetch();

  setInterval(fetch, 2000);

}).call(this);
